---
- name: Installing nano
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: nano
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing gedit-plugins
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: gedit-plugins
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing visual studio code
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: code
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing texlive-full
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: texlive-full
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing texmaker
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: texmaker
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes


#- name: Running apt --fix-broken install 
#  become_user: "{{ lookup('env','USER') }}"
#  ansible.builtin.shell: |
#   sudo apt --fix-broken install
#  args:
#    executable: /bin/bash
#    register: out
#- debug: 
#    var: out.stdout_lines

- name: Remove useless packages from the cache
  ansible.builtin.apt:
   autoclean: yes
- name: Run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes   



 

