---
  - name: Installing 
    become_user: "{{ lookup('env','USER') }}"
    shell: |
      sudo npm install -g configurable-http-proxy
    args:
 #    chdir: '{{playbook_dir}}/jupyterhub'
     executable: /bin/bash
    register: out
  - debug: var=out.stdout_lines




 

