---
#-----------------Using a script file located outside-----------------

# The following script will run various script

#----------------Proxy server-------------



  - name: Activate python3 virtual env 
    become_user: "{{ lookup('env','USER') }}"
    shell: |
      source '{{playbook_dir}}/jupyterhub/venv/bin/activate'
    args:
     executable: /bin/bash
    register: out
  - debug: var=out.stdout_lines


  - name: Running pytest
    become_user: "{{ lookup('env','USER') }}"
    shell: |
      pytest test_proxy.py
    args:
     chdir: '{{playbook_dir}}/jupyterhub/jupyterhub/tests'
     executable: /bin/bash
    register: out
  - debug: var=out.stdout_lines


#----------------LDAP Authenticator-------------



  - name: Activate python3 virtual env 
    become_user: "{{ lookup('env','USER') }}"
    shell: |
      source '{{playbook_dir}}/jupyterhub/venv/bin/activate'
    args:
     executable: /bin/bash
    register: out
  - debug: var=out.stdout_lines

  - name: Running pytest
    become_user: "{{ lookup('env','USER') }}"
    shell: |
      bash docker-ldap.sh
    args:
     chdir: '{{playbook_dir}}/pytest_ldap'
     executable: /bin/bash
    register: out
  - debug: var=out.stdout_lines

  - name: Running pytest
    become_user: "{{ lookup('env','USER') }}"
    shell: |
      pytest test_ldapauthenticator.py
    args:
     chdir: '{{playbook_dir}}/pytest_ldap/tests'
     executable: /bin/bash
    register: out
  - debug: var=out.stdout_lines

#----------------Native Authenticator-------------



  - name: Activate python3 virtual env 
    become_user: "{{ lookup('env','USER') }}"
    shell: |
      source '{{playbook_dir}}/jupyterhub/venv/bin/activate'
    args:
     executable: /bin/bash
    register: out
  - debug: var=out.stdout_lines


  - name: Running pytest
    become_user: "{{ lookup('env','USER') }}"
    shell: |
      pytest test_authenticator.py
    args:
     chdir: '{{playbook_dir}}/jupyterhub/nativeauthenticator/nativeauthenticator/tests'
     executable: /bin/bash
    register: out
  - debug: var=out.stdout_lines


 

