---
- name: Playbook to run apt install commands
  hosts: all
  become: true
  gather_facts: yes
  #pre_task:
  
  roles:
     - install_system    
     - install_editor
     - install_media
     - install_application
     - install_webbrowser
      
