---
- name: Installing octave
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: octave
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing gnuplot
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: gnuplot
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing gfortran
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: gfortran
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing gigolo
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: gigolo
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing tailscale
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: tailscale
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing timeshift
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: timeshift
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing zoom
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: zoom
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes

- name: Installing wps-office
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: wps-office
   state: latest
   install_recommends: yes
   only_upgrade:
   fail_on_autoremove: yes


#- name: Running apt --fix-broken install 
#  become_user: "{{ lookup('env','USER') }}"
#  ansible.builtin.shell: |
#   sudo apt --fix-broken install
#  args:
#    executable: /bin/bash
#    register: out
#- debug: 
#    var: out.stdout_lines

- name: Remove useless packages from the cache
  ansible.builtin.apt:
   autoclean: yes
- name: Run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes   



 

