---
#- name: Installing 
#  ansible.builtin.apt:
#   update_cache: true
#   update_cache_retries: 10
#   pkg: 
#   - htop
#   - tree
#   - apache2
#   state: latest
#  
#  only_upgrade:
#   fail_on_autoremove: yes
  

- name: Installing htop
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: htop
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing make
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: make
   state: latest  
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing git
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: git
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing fish
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: fish
   state: latest   
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing tree
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: tree
   state: latest  
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing tmux
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: tmux
   state: latest  
   only_upgrade:
   fail_on_autoremove: yes
   
   

- name: Installing blueman
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: blueman
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing cifs-utils
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: cifs-utils
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing curl
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: curl
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing default-jdk
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: default-jdk
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing jd-gui
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: jd-gui
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing net-tools
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: net-tools
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing npm
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: npm
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing openssh-server
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: openssh-server
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing smb-client
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: smb-client
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

- name: Installing unrar
  ansible.builtin.apt:
   update_cache: true
   update_cache_retries: 10
   name: unrar
   state: latest
   only_upgrade:
   fail_on_autoremove: yes
   

#- name: Running apt --fix-broken install 
#  become_user: "{{ lookup('env','USER') }}"
#  ansible.builtin.shell: |
#   sudo apt --fix-broken install
#  args:
#    executable: /bin/bash
#    register: out
#- debug: 
#    var: out.stdout_lines

- name: Remove useless packages from the cache
  ansible.builtin.apt:
   autoclean: yes
- name: Run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes   



 

